=== 13voron777/WEB_SERVICES/Intro_XML/src/LAB1/plane1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="charsType">
    <xs:sequence>
      <xs:element type="xs:string" name="type"/>
      <xs:element name="crew_seats">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="8"/>
            <xs:enumeration value="7"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="load_capacity">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="5000"/>
            <xs:enumeration value="4800"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="passengers">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="200"/>
            <xs:enumeration value="196"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="radar"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="parametersType">
    <xs:sequence>
      <xs:element name="length">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="100"/>
            <xs:enumeration value="90"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="width">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="12"/>
            <xs:enumeration value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="height"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="priceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="currency" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="planeType">
    <xs:sequence>
      <xs:element name="model">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Boeing 737"/>
            <xs:enumeration value="Airbus A330"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="USA"/>
            <xs:enumeration value="France"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="charsType" name="chars"/>
      <xs:element type="parametersType" name="parameters"/>
      <xs:element type="priceType" name="price"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="planeType" name="plane" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== 13voron777/WEB_SERVICES/Intro_XML/src/LAB1/plane.xml
<?xml version="1.0" encoding="UTF-8" ?>

<root xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation = "plane1.xsd">

    <plane id="BX-DSL">
        <model>Boeing 737</model>
        <origin>USA</origin>
        <chars>
            <type>passenger</type>
            <crew_seats>8</crew_seats>
            <load_capacity>5000</load_capacity>
            <passengers>200</passengers>
            <radar>yes</radar>
        </chars>
        <parameters>
            <length>100</length>
            <width>12</width>
            <height>5</height>
        </parameters>
        <price currency="USD">100_000_000</price>
    </plane>

    <plane id="SR-LSM">
        <model>Airbus A330</model>
        <origin>France</origin>
        <chars>
            <type>passenger</type>
            <crew_seats>7</crew_seats>
            <load_capacity>4800</load_capacity>
            <passengers>196</passengers>
            <radar>yes</radar>
        </chars>
        <parameters>
            <length>90</length>
            <width>10</width>
            <height>5</height>
        </parameters>
        <price currency="USD">95_000_000</price>
    </plane>

</root>
